"""Storage protocol — the abstraction boundary. No SQL outside sqlite_store.py."""

from typing import Protocol

from backend.models import BunqToken, PendingTool, Profile, Session, Turn


class Storage(Protocol):
    def get_profile(self, user_id: str) -> Profile | None: ...

    def upsert_profile(self, profile: Profile) -> None: ...

    def create_session(self, user_id: str) -> Session: ...

    def get_session(self, session_id: str) -> Session | None: ...

    def get_latest_session(self, user_id: str) -> Session | None: ...

    def list_sessions(self, user_id: str, limit: int = 20) -> list[Session]: ...

    def touch_session(self, session_id: str) -> None: ...

    def append_turn(self, session_id: str, turn: Turn) -> None: ...

    def list_turns(self, session_id: str, include_hidden: bool = False) -> list[Turn]: ...

    def put_pending_tool(self, session_id: str, pending: PendingTool) -> None: ...

    def get_pending_tool(self, session_id: str, tool_use_id: str) -> PendingTool | None: ...

    def clear_pending_tool(self, session_id: str, tool_use_id: str) -> None: ...

    def get_bunq_token(self, user_id: str) -> BunqToken | None: ...

    def put_bunq_token(self, user_id: str, token: BunqToken) -> None: ...
