services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SQLITE_PATH=/tmp/bunq_nest.db
      - AWS_DEFAULT_REGION="us-east-1"
      - AWS_ACCESS_KEY_ID="ASIAVPMCBMT5ZZGKMRYA"
      - AWS_SECRET_ACCESS_KEY="1pelf2nvuTuh3eRkbR3gmTTTYsdeZSXX8bR4lj77"
      - AWS_SESSION_TOKEN="IQoJb3JpZ2luX2VjEMn//////////wEaCXVzLWVhc3QtMSJIMEYCIQCLLp8S1OPUiaooybbirp92EtgyjJYlALHAQf6QTUuIbAIhAIxpzwfw9SQEbYJaBdy5XciMvnhOfKX/C6TP4LhjzhnRKqICCJL//////////wEQABoMMzc2NjE5MjMwNDU5IgwMCag1pIcSe7+vpEAq9gENc1Dgw08bxCuIAVj7TMyLg8KyxYD14DTXnOwNAqgupHBNCPVJWijOnua7Q9LXohJI+aZ7GaR6bWxNaefvFC8Ci+rFiMKVskhFaXVmQeFZNyzD9UXnSMLB1vzOw0aIXfYR41Arq5/AtM/qBIyDiMsLUyULKSU0AOJ0M+3cPYLnK18a3X+iyrHQ8swUb2+Q5rUTccksJkNN3lOuCgo9nO86/50Ci5RpVQkB2abHwwsyLOoPRtjOyv9kabyZ2wa73Z5cjrJTJbYKD8Bt67KibM8fxLMUUCQrOFc77e0bJA1qgqoSiC01QpAQUxHXpac28GQOpxk5KAIwwfOxzwY6nAHHuIJEtVpMoFswIYSQc2mDHXubaZsTv6TBrUQPtP27ffmUum8WljpuK8DZ5MxRiJcGZ91hqaaxY0zKXj+EMEOOrBgCFOUS86kFw82DMFJcMHajSUjee5xepAjR4ye/JdopbLmeMBq5EXH3DAG2OHRLtMrrIfs+tYrWsDUmU/mxB1DddULkx/WekBdTif+oQqzo9rS7lMxjLgJ169o="
    volumes:
      - ./backend:/app/backend

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - API_PROXY_TARGET=http://backend:8000
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/vite.config.ts:/app/vite.config.ts
