services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - SQLITE_PATH=/tmp/bunq_nest.db
    volumes:
      - ./backend:/app/backend

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
